version: '3.5'
services:
  scraper:
    container_name: scraper
    build:
      dockerfile: ./scraper/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./base:/base

  server:
    container_name: flask
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./base:/base
    links:
      - scraper
  