version: '3.5'
services:
  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./base/base.db:/base/base.db

  server:
    container_name: flask
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./base/base.db:/base/base.db
    links:
      - scraper
  